version: "3.9"
services:
  runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    volumes:
      - runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config.toml:/etc/gitlab-runner/config.toml

volumes:
  runner-config:
